baseURL = "https://dmachard.github.io/"
languageCode = "en-US"
title = "My technical gists"
theme = "gists"
pygmentsCodeFences = true
paginate = 10

[params]
  author = "Denis Machard"
  resume = "My technical gists"
  email = "d.machard@gmail.com"
  description = "Infrastructure architect by profession but always consider himself as a developer and an open source enthusiast."
  github = "dmachard"
  mastodon = "https://fosstodon.org/@dmachard"
  keywords = "blog, technical"
  rss = true
  lastmod = true
  favicon = "/images/profile.png"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
