baseURL = "https://dmachard.github.io/"
languageCode = "en-US"
title = "My technical gists"
theme = "gists"
pygmentsCodeFences = true
paginate = 5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  author = "Denis Machard"
  resume = "My technical gists"
  email = ""
  description = "Infrastructure background, developer mindset. I build things for pleasure."
  github = "dmachard"
  mastodon = "https://fosstodon.org/@dmachard"
  keywords = "blog, technical"
  rss = true
  favicon = "/images/avatar.png"
  avatar = "/images/profile.png"